services:
  # -----------------------------
  # 1) Backend: Node/Express + Socket.IO
  # -----------------------------
  - type: web
    name: trivia-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci
    startCommand: |
      node backendapp.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      # ----- Required (set these in the Render dashboard or in a Render Env Group) -----
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      # The frontend origin Render will serve (fill after the frontend deploys)
      # Example: https://trivia-frontend.onrender.com
      - key: CLIENT_ORIGIN
        value: https://REPLACE_WITH_FRONTEND_URL

      # If you’re behind a proxy and setting Secure cookies, trust proxy is recommended in your app:
      # app.set('trust proxy', 1)
      # (No env var needed here; just a reminder.)

  # -----------------------------
  # 2) Frontend: Vite React (Static Site)
  # -----------------------------
  - type: static
    name: trivia-frontend
    plan: free
    rootDir: frontend
    buildCommand: |
      npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      # Point the built frontend at the backend API URL (fill after the backend deploys).
      # Example: https://trivia-backend.onrender.com
      - key: VITE_API_URL
        value: https://REPLACE_WITH_BACKEND_URL

    # Single Page App fallback so client-side routing works
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html