services:
  # Backend: Node/Express + Socket.IO
  - type: web
    name: trivia-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: |
      npm ci
    startCommand: |
      node backendapp.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # After the frontend deploys, set this to its URL (e.g. https://your-frontend.onrender.com)
      - key: CLIENT_ORIGIN
        value: https://REPLACE_WITH_FRONTEND_URL

staticSites:
  # Frontend: Vite React (serves /dist)
  - name: trivia-frontend
    rootDir: frontend
    plan: free
    buildCommand: |
      npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      # After the backend deploys, set this to its URL (e.g. https://your-backend.onrender.com)
      - key: VITE_API_URL
        value: https://REPLACE_WITH_BACKEND_URL
    # SPA fallback so client-side routing works
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html