services:
  # --- Backend: Node/Express + Socket.IO ---
  - type: web
    name: trivia-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm ci || npm install"
    startCommand: node backendapp.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      # The frontend host (no scheme). Your code will build https://<host>
      - key: CLIENT_ORIGIN_HOST
        fromService:
          type: web
          name: trivia-frontend
          property: host

  # --- Frontend: Vite build served by a tiny Node process ---
  - type: web
    name: trivia-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm ci || npm install && npm run build"
    startCommand: |
      npx serve -s dist -l $PORT
    autoDeploy: true
    envVars:
      # The backend host (no scheme). Vite code will build https://<host>
      - key: VITE_API_HOST
        fromService:
          type: web
          name: trivia-backend
          property: host