services:
  # Backend: Node/Express + Socket.IO
  - type: web
    name: trivia-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: |
      npm ci
    startCommand: |
      node backendapp.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # Pull the frontend URL into backend CORS
      - key: CLIENT_ORIGIN
        fromService:
          type: web
          name: trivia-frontend
          property: url

  # Frontend: serve Vite build via a tiny Node server (no staticSites needed)
  - type: web
    name: trivia-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: |
      npm ci && npm run build
    startCommand: |
      npx serve -s dist -l $PORT
    autoDeploy: true
    envVars:
      # Pull the backend URL into the frontend at build time
      - key: VITE_API_URL
        fromService:
          type: web
          name: trivia-backend
          property: url